//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AuditDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AuditDBEntities object using the connection string found in the 'AuditDBEntities' section of the application configuration file.
        /// </summary>
        public AuditDBEntities() : base("name=AuditDBEntities", "AuditDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuditDBEntities object.
        /// </summary>
        public AuditDBEntities(string connectionString) : base(connectionString, "AuditDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuditDBEntities object.
        /// </summary>
        public AuditDBEntities(EntityConnection connection) : base(connection, "AuditDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_audit> tbl_audit
        {
            get
            {
                if ((_tbl_audit == null))
                {
                    _tbl_audit = base.CreateObjectSet<tbl_audit>("tbl_audit");
                }
                return _tbl_audit;
            }
        }
        private ObjectSet<tbl_audit> _tbl_audit;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_audit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_audit(tbl_audit tbl_audit)
        {
            base.AddObject("tbl_audit", tbl_audit);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AuditDBModel", Name="tbl_audit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_audit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_audit object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tbl_audit Createtbl_audit(global::System.Int32 id)
        {
            tbl_audit tbl_audit = new tbl_audit();
            tbl_audit.id = id;
            return tbl_audit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String system
        {
            get
            {
                return _system;
            }
            set
            {
                OnsystemChanging(value);
                ReportPropertyChanging("system");
                _system = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("system");
                OnsystemChanged();
            }
        }
        private global::System.String _system;
        partial void OnsystemChanging(global::System.String value);
        partial void OnsystemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String logged_in_user
        {
            get
            {
                return _logged_in_user;
            }
            set
            {
                Onlogged_in_userChanging(value);
                ReportPropertyChanging("logged_in_user");
                _logged_in_user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logged_in_user");
                Onlogged_in_userChanged();
            }
        }
        private global::System.String _logged_in_user;
        partial void Onlogged_in_userChanging(global::System.String value);
        partial void Onlogged_in_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String role
        {
            get
            {
                return _role;
            }
            set
            {
                OnroleChanging(value);
                ReportPropertyChanging("role");
                _role = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("role");
                OnroleChanged();
            }
        }
        private global::System.String _role;
        partial void OnroleChanging(global::System.String value);
        partial void OnroleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String event_name
        {
            get
            {
                return _event_name;
            }
            set
            {
                Onevent_nameChanging(value);
                ReportPropertyChanging("event_name");
                _event_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("event_name");
                Onevent_nameChanged();
            }
        }
        private global::System.String _event_name;
        partial void Onevent_nameChanging(global::System.String value);
        partial void Onevent_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String entity
        {
            get
            {
                return _entity;
            }
            set
            {
                OnentityChanging(value);
                ReportPropertyChanging("entity");
                _entity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("entity");
                OnentityChanged();
            }
        }
        private global::System.String _entity;
        partial void OnentityChanging(global::System.String value);
        partial void OnentityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.String _created_date;
        partial void Oncreated_dateChanging(global::System.String value);
        partial void Oncreated_dateChanged();

        #endregion

    
    }

    #endregion

    
}
